"""Add password hash to doctors

Revision ID: 82e9f06e399c
Revises: 458da680c4e9
Create Date: 2026-03-12 21:01:51.539002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e9f06e399c'
down_revision: Union[str, Sequence[str], None] = '458da680c4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('password_hash', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'password_hash')
    # ### end Alembic commands ###
