"""Add doctors appointments records pharmacy medicines

Revision ID: c891d570c6ab
Revises: b71766e1fa21
Create Date: 2026-03-12 18:08:17.513626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c891d570c6ab'
down_revision: Union[str, Sequence[str], None] = 'b71766e1fa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
